(op! 'ramp "myRamp")
(op! 'noise "noise1")
(op! 'composite "composite")
(op! 'cuboid "cuboid1")
(op! 'window "window")
(op! 'standard-material "mat")

(param! (op "noise1") "Strength" (/ *time* 100))
(param! (op "myRamp") "Mode" 0)
(param! (op "window") "Texture" (op "mat"))
(param! (op "mat") "Texture" (op "composite"))